### ISSUE TITLE
Port for Ag team

### ISSUE THREAD

**Issue by znmeb** [hackoregon/urbandev-vagrant#3]
The Ag team needs a Vagrant box too - can we get a port / fork of this one? As far as I know we don't need MySQL, just PostgreSQL

**Comment by johnzimm** [comment]
I'll spend some time on this tonight.  I'll get all the puppet scripts converted to ansible.  I'm more familiar with that now and that's what was taught in the devops class.  I think the RVM install to support puppet is what is hanging in the other issue you reported.  Puppet is better in a long term configuration management scenario rather than bootstrapping without a puppet master.

**Comment by znmeb** [comment]
OK ... I'll close this one now that we have a cropcompass-vagrant repo
